Adds max request error handling
yalelibrary/yul-dc-management pull request #1102
Opened 2022-11-30 22:26 UTC by K8Sewell

# Summary
Adds error handling for permission requests that exceed the max queue length per permission set.

# Related Ticket
[#2290](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2290)

2022-12-01 14:35 UTC, mikeapp requested changes

2022-12-01 14:35 UTC, mikeapp commented on app/controllers/api/permission_requests_controller.rb
> +    approver = User.with_role(:approver, permission_set).first
Let's leave the approver `null` when the request is created.   We'll use the value to record the user who actually approves the request.

2022-12-01 17:12 UTC, K8Sewell commented on app/controllers/api/permission_requests_controller.rb
> +    approver = User.with_role(:approver, permission_set).first
That makes sense.  Just updated it so that user is no longer required to create a permission request.

2022-12-02 18:39 UTC, mikeapp approved these changes

2022-12-02 18:39 UTC, merged