Bump test coverage
yalelibrary/yul-dc-management pull request #1117
Opened 2023-01-03 21:25 UTC by K8Sewell

# Summary
Coverage dropped below our target of 97% and this MR brings the coverage back up.

2023-01-09 18:38 UTC, mikeapp requested changes

2023-01-09 18:38 UTC, mikeapp commented on config/routes.rb
> +    resources :permission_requests, only: [:create, :update]
I think this `:update` route should also be removed?

2023-01-09 19:01 UTC, jpengst commented on config/routes.rb
> +    resources :permission_requests, only: [:create, :update]
Good catch, thanks!

2023-01-10 18:23 UTC, mikeapp approved these changes

2023-01-10 18:39 UTC, merged