Add OwP auth header
yalelibrary/yul-dc-management pull request #1426
Opened 2024-08-20 17:37 UTC by K8Sewell

# Summary
Adds auth header for open with permission

# Related Ticket
[#2877](https://github.com/yalelibrary/YUL-DC/issues/2877)

2024-08-20 18:08 UTC, martinlovell requested changes
You should not set the header on the response. 

This would mean that if someone requested without the key, they would get the key in the response...which is supposed to be a secret.

2024-08-20 18:12 UTC, jpengst approved these changes

2024-08-21 16:29 UTC, K8Sewell commented
> You should not set the header on the response.
> 
> This would mean that if someone requested without the key, they would get the key in the response...which is supposed to be a secret.

Updated this PR to no longer provide auth tokens back to blacklight.

2024-08-21 18:05 UTC, jpengst approved these changes

2024-08-22 13:02 UTC, martinlovell requested changes

2024-08-22 13:02 UTC, martinlovell commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!, except: [:check_authorization]
You don't need the except for regular methods not tied directly to a route/request. It will only get called on methods triggered because of a route.
(Here and a couple other placed.)

2024-08-22 13:02 UTC, martinlovell commented on app/controllers/api/permission_sets_controller.rb
> +    response.set_header('Authorization', "Bearer #{ENV['OWP_AUTH_TOKEN']}")
One last reponse to remove the header from

2024-08-22 13:54 UTC, K8Sewell commented on app/controllers/api/permission_sets_controller.rb
> +    response.set_header('Authorization', "Bearer #{ENV['OWP_AUTH_TOKEN']}")
removed

2024-08-22 13:54 UTC, K8Sewell commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!, except: [:check_authorization]
Updated this in most recent commit.  Thanks for the catch!

2024-08-22 14:18 UTC, martinlovell approved these changes

2024-08-22 14:20 UTC, merged