Ingest event again
yalelibrary/yul-dc-management pull request #416
Opened 2020-11-24 18:59 UTC by maxkadel

2020-11-24 20:15 UTC, orangewolf requested changes
one super small change and the bigger question - what are we hoping to gain from this code change. we're adding a new model to the code and (I assume) removing one eventually?

2020-11-24 20:15 UTC, orangewolf commented on app/controllers/batch_processes_controller.rb
> +      @notes = @child_object.notes_for_batch_process(@batch_process)
this is a very welcome change

2020-11-24 20:15 UTC, orangewolf commented on app/models/child_object.rb
> +    ie = IngestEvent.new(
just do create! instead of new and then save!, that way you do not alloc and then free a variable from memory

2020-11-24 22:33 UTC, orangewolf approved these changes
thanks for the clarification

2020-11-25 14:27 UTC, maxkadel commented
> one super small change and the bigger question - what are we hoping to gain from this code change. we're adding a new model to the code and (I assume) removing one eventually?

For posterity: 
My thinking was that
1. I have an untested hypothesis (part of why I'm about to play with it on collections-test) that searching the fields directly, rather than within the json parameters of the notifications, will be faster
2. We're creating lots of notifications that are not necessarily actionable by a single user
3. This frees us up to only notify the user who created the batch process, and only tell them what they are more likely to care about (the final result, when they've all reach some kind of "failed or other" end state), and for those not to get mixed in with the status notifications. I was going to start on that but I felt like I needed some more input on what people care about and how to determine it

2020-11-25 16:34 UTC, merged