hide the delayed jobs menu option for non sysadmins
yalelibrary/yul-dc-management pull request #571
Opened 2021-03-22 23:15 UTC by alishaevn

# Ticket
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1117

# Resources
- https://github.com/ejschmitt/delayed_job_web#authenticating-with-devise-and-warden
- https://stackoverflow.com/a/38779554/8079848

2021-03-23 19:04 UTC, FCRodriguez7 approved these changes

2021-03-23 19:05 UTC, FCRodriguez7 requested changes
Should this have a test?

2021-03-23 23:16 UTC, alishaevn commented
> Should this have a test?

I thought about that...but then noticed that there aren't any tests surrounding this engine at all. but I suppose I can add one.

2021-03-24 13:49 UTC, FCRodriguez7 approved these changes

2021-03-24 13:49 UTC, FCRodriguez7 approved these changes

2021-03-24 14:43 UTC, merged